### ISSUE TITLE
Docker Hub builds are only tagged with 'latest'

### ISSUE THREAD

**Issue by whi-tw** [scnewma/nest_exporter#4]
Hello!

Sorry, me again. It looks like you're only tagging the docker repos with 'latest' (`hooks/post_push` has been removed in 6f60556943da9ebd5a0d646aa5c3ef16d8919d85, which caused docker hub to add extra tags to the built image - without that, it will only tag `latest`.

Would it be possible to add some extra per-build tags, so a container can be pinned to a specific version?

**Comment by scnewma** [comment]
Hey Tom!

Yea, I changed the build process in Docker Hub to be triggered off of tags pushed to this repository. I totally forgot to cut a release on your contribution last week. That is done now. You should be able to use the `v0.2.0` tag to pull the new Docker image.

**Comment by whi-tw** [comment]
⭐️⭐️⭐️⭐️⭐️

Perfect!

Deployed happily - thank you!
